### ISSUE TITLE
Aditional </nav>

### ISSUE THREAD

**Issue by alcastronava** [darrel-oneil/PaginationTagHelper#1]
Hi Darrel
First I want to thank you for this helpfull tool.

I have an issue, look this... and take note on the final `</nav>` tag, its duplicated

`<nav role="navigation" aria-label="Pagination" class="pagination-tag-helper"><ul class="pagination"><li class="page-item disabled" tabindex="-1"><a class="page-link" aria-label="go to first page">&#171;</a></li><li class="page-item disabled" tabindex="-1"><a class="page-link" aria-label="go to previous page">‹</a></li><li class="page-item disabled" tabindex="-1"><a class="page-link" aria-label="skip back to page 1">&#46;&#46;</a></li><li class="page-item active"><a class="page-link" aria-current="true" aria-label="page 1" href="/Allergies/Search?page=1&pageSize=5" data-ajax="true" data-ajax-method="Post" data-ajax-begin="OnBegin()" data-ajax-complete="OnComplete()" data-ajax-update="#search-list" data-ajax-mode="replace">1</a></li><li class="page-item"><a class="page-link" aria-label="go to page 2" href="/Allergies/Search?page=2&pageSize=5" data-ajax="true" data-ajax-method="Post" data-ajax-begin="OnBegin()" data-ajax-complete="OnComplete()" data-ajax-update="#search-list" data-ajax-mode="replace">2</a></li><li class="page-item disabled" tabindex="-1"><a class="page-link" aria-label="skip forward to page 2">&#46;&#46;</a></li><li class="page-item"><a class="page-link" aria-label="go to next page" href="/Allergies/Search?page=2&pageSize=5" data-ajax="true" data-ajax-method="Post" data-ajax-begin="OnBegin()" data-ajax-complete="OnComplete()" data-ajax-update="#search-list" data-ajax-mode="replace">›</a></li><li class="page-item"><a class="page-link" aria-label="go to last page" href="/Allergies/Search?page=2&pageSize=5" data-ajax="true" data-ajax-method="Post" data-ajax-begin="OnBegin()" data-ajax-complete="OnComplete()" data-ajax-update="#search-list" data-ajax-mode="replace">&#187;</a></li></ul></nav></nav>`

This come from...

```
<pager link-url="@Url.Action("Search", "Allergies")"
       page="Model.CurrentPage"
       page-size="Model.PageSize"
       total-items="Model.TotalItemCount"
       previous-page-text="‹"
       next-page-text="›">
    <ajax-options update-target-id="search-list"
            on-begin="OnBegin()"
            on-complete="OnComplete()">
    </ajax-options>
</pager>
```

Thanks again, I hope that you find and solve this issue.
Alfredo

**Comment by darrel-oneil** [comment]
Hi Alfredo,

Thanks from bringing that to my attention. This has now been fixed.
